### ISSUE TITLE
Can't `npm install` as root, permission denied

### ISSUE THREAD

**Issue by cowboy** [endpoints/ember-data-endpoints#24]
If I try to `npm install ember-data-endpoints` as `root`, the installation explodes. Is there any way to do this without Bower?

```
cowboy@box:~$ sudo su
root@box:/home/cowboy# cd /tmp
root@box:/tmp# mkdir test && cd test
root@box:/tmp/test# echo "{}" > package.json
root@box:/tmp/test# npm install ember-data-endpoints
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json @ No license field.
\
> ember-data-endpoints@4.0.0 postinstall /tmp/test/node_modules/ember-data-endpoints
> bower install

/usr/lib/node_modules/bower/node_modules/configstore/index.js:56
                throw err;
                      ^
Error: EACCES, permission denied '/root/.config/configstore/bower-github.yml'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (evalmachine.<anonymous>:500:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:352:15)
    at Object.create.all.get (/usr/lib/node_modules/bower/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/bower/node_modules/configstore/index.js:27:44)
    at readCachedConfig (/usr/lib/node_modules/bower/lib/config.js:22:23)
    at defaultConfig (/usr/lib/node_modules/bower/lib/config.js:11:24)
    at Object.<anonymous> (/usr/lib/node_modules/bower/lib/index.js:40:32)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "node" "/usr/bin/npm" "install" "ember-data-endpoints"
npm ERR! node v0.12.7
npm ERR! npm  v2.13.0
npm ERR! code ELIFECYCLE

npm ERR! ember-data-endpoints@4.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ember-data-endpoints@4.0.0 postinstall script 'bower install'.
npm ERR! This is most likely a problem with the ember-data-endpoints package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls ember-data-endpoints
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/test/npm-debug.log
root@box:/tmp/test#
```

**Comment by cowboy** [comment]
Looks like 2e4ffb296b7b69dbb4729f01be6b0dcfb79078c0 fixed this. Thanks!
